//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cache_Money_Questions
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProgress
    {
        public string Username { get; set; }
        public int TotalAsked { get; set; }
    }
}
